language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "start to build image udagram api feed and push image to dockerhub"

before_script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

script:
  - docker tag udagram-api-feed vubuivn/udagram-api-feed:version2
  - docker tag udagram-api-user vubuivn/udagram-api-user:version2
  - docker tag udagram-frontend vubuivn/udagram-frontend:version2
  - docker tag udagram-reverseproxy vubuivn/udagram-reverseproxy:version2
  - docker image ls -a


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vubuivn/udagram-api-feed:version1
  - docker push vubuivn/udagram-api-user:version1
  - docker push vubuivn/udagram-frontend:version1
  - docker push vubuivn/udagram-reverseproxy:version1