language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "start to build image udagram api feed and push image to dockerhub"

before_script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

script:
  - docker tag udagram-api-feed quanhk711/udagram-api-feed:version2
  - docker tag udagram-api-user quanhk711/udagram-api-user:version2
  - docker tag udagram-frontend quanhk711/udagram-frontend:version2
  - docker tag udagram-reverseproxy quanhk711/udagram-reverseproxy:version2
  - docker image ls -a


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push quanhk711/udagram-api-feed:version1
  - docker push quanhk711/udagram-api-user:version1
  - docker push quanhk711/udagram-frontend:version1
  - docker push quanhk711/udagram-reverseproxy:version1