apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  credentials: W3VkYV0KYXdzX2FjY2Vzc19rZXlfaWQgPSBBU0lBVlZYRU1YRU5UUlpYUFdPQgphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSBxVTlDWDJ2U1EvbW84cE1wVHp0bVlLbHFOK1NMZXhVMWVqNE5nRUcvCmF3c19zZXNzaW9uX3Rva2VuID0gRndvR1pYSXZZWGR6RUNnYURNWDBhMFowK09ZYjBHbFJFQ0xWQVd2R09ZY2F3NDI2dlc5VEQxM1JmZmR3NzJreTZHbEVvaGNrcEpoT1A2emN2ZFdacG4xSG03ZzQ2YVlKRXUwbmw2MmlweWpwdFlYNmk4Q2o5WjRGR1BIQk1EUCtZOGI1UENXQVo1b0RuZzNvTWV5bURraVJiNDZtNSszdzhXYmtoYXExZTB6V3lKbDRaYi9jZ0htN3FEM2xxRmdwb092c3ZsQ3JoMFBmSENJOWFQQ1hLOVRYdkdNTkRPc2xsbnI3bWNEWkxKUUpqTlhQdFBQNFNrUXd2dFJSWTZrOWE2cDlHNHdKZmMzVDF6OVozMlZiSDh4YWp3T0c2ZEVvV2NVc2R5QjBOZ28xTnZ6cmJkc1BLUXpvSWN1ZGpjaitZQ2pTNUkyY0JqSXQ4Z3V3L0ZZVk93RkFYeWF3a3pydHZjWW1ublJRVFJUUzBpUWtlQW9XTkg1Tmhza3cyL2ZZcVk0TU9tOTA=