apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-feed
  name: backend-feed
spec:
  selector:
    service: api-feed
  ports:
    - name: "api-feed-8080"
      port: 8080
      targetPort: 8080