apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-user
  name: backend-user
spec:
  selector:
    service: api-user
  ports:
    - name: "api-user-8080"
      port: 8080
      targetPort: 8080
